config/routes.rb
Dreamkeeper::Application.routes.draw do
 

  resources :users
  resources :contacts
  resources :sessions

  root :to => 'pages#home'

  get 'user', to: "users#new", as: "user"
  get 'login', to: "sessions#new", as: "login"
  get 'logout', to: "sessions#destroy", as: "logout"

  match "home", to: "pages#home"

  match "goat", to: "pages#goat"

  match "jewelry", to: "pages#jewelry"

  match "fiber", to: "pages#fiber"

  match "locations", to: "pages#locations"

  match "pictures", to: "pages#pictures"
  
  match "contacts", to: "contacts#new"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :message, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password_digest, :password_confirmation

  validates_uniqueness_of :email
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
    
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    if @contact.save

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Your message has been sent to Dream Keeper Farms!' }
        format.json { render json: @contact, status: :created, location: @contact }
        ContactMailer.contact_us(@contact).deliver
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end
end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def goat
  end

  def jewelry
  end

  def fiber
  end

  def locations
  end

  def pictures
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

    def create
        user = User.find_by_email(params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_url, notice: "Logged in!"
        else
          flash.now.alert = "Email or password is invalid"  
        render "new"    
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(params[:user])
        if @user.save
            redirect_to root_url, notice: "You are now an Admin!"
        else
            render "new"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h5> We offer our products in every scent imaginable, using pure essential oil whenever possible. If you don't see what you are looking for please let us know and we will make it for you.</h5>
  <br></br>
<div class="contact_form">
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message, :rows => "9" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
</div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.name %></td>
    <td><%= contact.email %></td>
    <td><%= contact.message %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1> Contact Us!</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @contact.name %>
</p>

<p>
  <b>Email:</b>
  <%= @contact.email %>
</p>

<p>
  <b>Message:</b>
  <%= @contact.message %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link  href='http://fonts.googleapis.com/css?family=Raleway' rel="stylesheet" type="text/css" >

  <title>Dream Keeper Farm</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 
</head>

<body>
  <div class="sign_in_form">
    <% if current_user %>
      Logged in as <%= current_user.email %>
      <%= link_to "Log Out", session_path("current"), method: "delete" %>
  <% else %>
    <%= link_to "Sign Up", new_user_path %>or
    <%= link_to "Log In", new_session_path %>
  <% end %>
  </div>

    <%= flash.each do |name, msg| %>
      
    <% end %>

<br></br>
<div class="logo">
<%= image_tag "logo.png" %>
<br></br>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
            <ul class="nav pull-right">
            <li><%=link_to "Home", "/home", id: "logo-nav" %></li>
            <li><%=link_to "Goat Products", "/goat", id: "logo-nav" %></li>
            <li><%=link_to "Fiber Products", "/fiber", id: "logo-nav" %></li>
            <li><%=link_to "Jewelry", "/jewelry", id: "logo-nav" %></li>
            <li><%=link_to "Locations", "/locations", id: "logo-nav" %></li>
            <li><%=link_to "Pictures", "/pictures", id: "logo-nav" %></li>
            <li><%=link_to "Contact", "/contacts/new", id: "logo-nav" %></li>
            </ul>
          </div>
        </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/fiber.html.erb
<h1>Fiber Products</h1>

<div class="fiber_image_2">
<%= image_tag "yarn two.jpg" %>
</div>
<br></br>
<div class="fiber_image_1">
<%= image_tag "yarn one.jpg" %>
</div>
<br></br>

<h3>We are still spinning away! 

We take custom spinning projects and are always looking for a new challenge.  Bring us your dog, cat, coyote, etc hair and we will be more than happy to create a lasting memory for you.  We also spins traditional fibers.</h3>

app/views/pages/goat.html.erb
<h1>Goat Milk Products</h1>

<div class="goat_image">
<%= image_tag "goat_page.jpg" %>
</div>

<br></br>


<h3>Goat milk has long been treasured by man. It is alkaline and naturally homogenized making it a perfect match for the human body. Goat milk does wonders for the body inside and out. Nigerian Dwarfs are a miniature dairy goat maturing around 50 lbs.  heir milk is superior in taste, texture and butterfat to full size dairy goats making it “the cream of the cream of the crop!”</h3>
<br></br>


<h3> To get the maximum benefit of the milk we use the base as a carrier, a way to get the milk where it needs to go. Our creams, lotions and potions contain 25% goat milk, our soaps contain 15 %. Since our milk comes straight from our farm it is never more than a week old. Our “staff” of goats has full medical coverage with annual physicals by the Vet. What does this have to do with the milk?  Healthy goats = Healthy milk.</h3>

app/views/pages/home.html.erb
<div class="home_image">
<%= image_tag "KCHayGoatPile (3).JPG" %>
</div>



<h3>At Dream Keeper Farm one thing remains constant, this is the place where our dreams have come true!</h3>

<h3>We offer:</h3>
<br></br>

<div class="bulletpoint_1">
<li>Goat Milk Lotions</li>
</div>

<div class="bulletpoint_1">
<li>Creams</li>
</div>

<div class="bulletpoint_1">
<li>Soaps</li>
</div>

<div class="bulletpoint_1">
<li>Bath Items</li>
</div>

<div class="bulletpoint_1">
<li>Herbal Products</li>
</div>

<div class="bulletpoint_1">
<li>Jewelry</li>
</div>

<div class="bulletpoint_1">
<li>Fresh Eggs</li>
</div>

<div class="bulletpoint_1">
<li>Hand Spinning</li>
</div>

<div class="bulletpoint_1">
<li>Fiber Products</li>
</div>

<div class="bulletpoint_1">
<li>Raw Goat Milk</li>
</div>
<br></br>

<h3>If there is something you think we can help you with just let us know!</h3>

app/views/pages/jewelry.html.erb
<h1>Jewelry</h1>

<h3>  
Our entire collection is handmade ranging from the whimsical fun pieces to the vintage heirloom pieces. All are original designs, most being one of a kind works of art. All pieces can be adjusted to needed sizes. Custom work is available. </h3>

<div class="jewelry_images">
<%= image_tag "moon lady.jpg" %>

<%= image_tag "fall agate.jpg" %>

<%= image_tag "blue green agate.jpg" %>

<%= image_tag "bunny herb.jpg" %>

<%= image_tag "moon mama one.jpg" %>

<%= image_tag "jewels one.jpg " %>

<%= image_tag "na.jpg" %>

<%= image_tag "river rock two.jpg" %>

<%= image_tag "pendant.jpg" %>

<%= image_tag "the cuffs.jpg" %>

<%= image_tag "rainbow cuff.jpg" %>

<%= image_tag "turq cuff.jpg" %>

<%= image_tag "purple cuff.jpg" %>

<%= image_tag "peyoty one.jpg" %>

<%= image_tag "peyoty two.jpg" %>

<%= image_tag "memory bracletes.jpg" %>

<%= image_tag "silver braclet two.jpg" %>

<%= image_tag "gold wire braclet.jpg" %>
</div>

app/views/pages/locations.html.erb
<h1>Places you can find us when not at the farm:</h1>

<h3>We will be back at the Warrenton Farmers Market in April 2013.</h3>
<br></br>
<div class="location_image">
<%= image_tag "SmallCrowd.JPG" %>
</div>

app/views/pages/pictures.html.erb
<h1>Pictures</h1>
<br></br>

<div class="picture_page_images">
<%= image_tag "orion.jpg" %>
<%= image_tag "romeo.jpg" %>
<%= image_tag "winston.jpg" %>
<%= image_tag "cheyenne.jpg" %>
<%= image_tag "dolly.jpg" %>
<%= image_tag "Clive.jpg" %>
<%= image_tag "mariana.jpg" %>
<%= image_tag "goat_1.JPG" %>
<%= image_tag "standing_goat.jpg" %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
     <div class="error_messages">
         <h2>Form is invalid</h2>
         <ul>
             <% @user.errors.full_messages.each do |message| %>
               <li><%= message %></li>
             <% end %>  
         </ul>
       </div>
    <% end %>

    <div class="field">
        <%= f.label :email %><br/>
        <%= f.text_field :email %>
    </div>
    <div class="field">
        <%= f.label :password %></br>
        <%= f.password_field :password %>
    </div>
    <div class="field">
        <%= f.label :password_confirmation %></br>
        <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions"><%= f.submit%></div>
    <% end %>